<?php 
if (isset($this->message)&&trim($this->message)!='') {
    ?>
<div class="container-fluid" style="margin-bottom: 20px;">
        <div class="col-lg-3 col-md-3"></div>
        <div class="col-lg-6 col-md-6" align='center' style='color: red;font-size: 40px;'>
            <?php
            echo $this->message;
            ?>
        </div>
        <div class="col-lg-3 col-md-3"></div>
    </div>
    <?php
}
?>
