<?php 

if (isset($this->message)&&trim($this->message)!='') {
    ?>
    <div class="row-fluid" style="margin-top: 20px;">
        <div class="col-lg-3 col-md-3"></div>
        <div class="col-lg-6 col-md-6" align='center' style='color: red;'>
            <?php
            echo $this->message;
            ?>
        </div>
        <div class="col-lg-3 col-md-3"></div>
    </div>
    <?php
}
?>
<div class="row-fluid" style="margin-top: 10px;">
    <?php     
    $buttons[]=array('onclick'=>"window.location = '".$this->baseUrl('/admin/user/index/page/'.$this->page)."'",'label'=>'Quay lại');
    $buttons[]=array('onclick'=>'document.form.submit();','label'=>'Lưu');
    echo $this->toolbar($buttons);
    ?>
</div>
<form name="form" enctype="multipart/form-data" id="form" action="<?php echo $this->url(); ?>" method="post">
    <div class="row-fluid" style="margin-top: 10px;">
        <div class="col-lg-4 col-md-4"></div>

        <div class="col-lg-12 col-md-12">
            <?php echo $this->form($this, $this->form, 1, $echo_form_tag = FALSE); ?>
        </div>

    </div>

</form>   

<script type="text/javascript">
    
    jQuery(function ($) {
        

        $("form").find("input").eq(0).focus();


        danh_xung_node = $("#danh_xung").parent().parent().clone();
        $("#danh_xung").parent().parent().remove();
        $("tbody").eq(0).prepend($(danh_xung_node));

    });

</script>



