<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/js/jqwidgets/styles/jqx.base.css" type="text/css" />
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jqwidgets/demos.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jqwidgets/jqxcore.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jqwidgets/jqxbuttons.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jqwidgets/jqxscrollbar.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jqwidgets/jqxpanel.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jqwidgets/jqxtree.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jqwidgets/jqxcheckbox.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jqwidgets/jqxmenu.js"></script>
<script type="text/javascript">
    var level,id;
    var contextMenuAll,contextMenu,contextMenuRoot;
</script>
<script type="text/javascript">
    function deleteItem(controller_name,level,id){
        $.ajax({
            url:'<?php echo $this->baseUrl();?>/'+controller_name+'/delete',
            type:'POST',
            data:{'level':level,'id':id},
            async: true,
            success: function (data1, textStatus, jqXHR) {
                
            }
        });
    }
    function addMucCon(controller_name,name_element) {
      if ( $.trim($(name_element).val())!='' ) {
          var selectedItem = $('#jqxTree').jqxTree('selectedItem');
            if (selectedItem != null) {
                var id_new;
                if ($("#is_public").is(":checked")){
                    is_public = "1";
                }
                else{
                    is_public = "0";
                }
                var temp = $.trim($(name_element).val());
                $.ajax({
                    url:'<?php echo $this->baseUrl();?>/'+controller_name+'/add',
                    type:'POST',
                    data:{'is_public':is_public,'level':level,'id':id,'title':$.trim($(name_element).val()),'content':$.trim($("#content").val())},
                    async: true,
                    success: function (data1, textStatus, jqXHR) {
                        $('#jqxTree').jqxTree('addTo', { label: temp }, selectedItem.element);

                        lis=$("#jqxTree li");
                        for(i=0;i<lis.length;i++){
                            if($(lis[i]).find('div').eq(0).html()==temp){
                                $(lis[i]).addClass('level_1').addClass('id_'+$.trim(data1));
                            }
                        }
                        id_new=data1;
                        attachContextMenu();
                    }
                });
            }
          dialog.dialog( "close" );

      }
      else{
          alert('Vui lòng nhập tên mục');
          $(name_element).focus();
      }

    }
    
    function editItem(controller_name,name_element) {
      if ( $.trim($(name_element).val())!='' ) {
          var selectedItem = $('#jqxTree').jqxTree('selectedItem');
            if (selectedItem != null) {
                if ($("#is_public_edit").is(":checked")){
                    is_public = "1";
                }
                else{
                    is_public = "0";
                }
                var temp = $.trim($(name_element).val());
                $.ajax({
                    url:'<?php echo $this->baseUrl();?>/'+controller_name+'/edit',
                    type:'POST',
                    data:{'is_public':is_public,'id':id,'title':$.trim($(name_element).val()),'content':$.trim($("#content_edit").val())},
                    async: true,
                    success: function (data1, textStatus, jqXHR) {
                        $('#jqxTree').jqxTree('updateItem',selectedItem.element, { label: temp } );
                        attachContextMenu();
                    }
                });
            }
          dialogEdit.dialog( "close" );

      }
      else{
          alert('Vui lòng nhập tên mục');
          $(name_element).focus();
      }

    }
    
    function isRightClick(event) {
        var rightclick;
        if (!event) var event = window.event;
        if (event.which) rightclick = (event.which == 3);
        else if (event.button) rightclick = (event.button == 2);
        return rightclick;
    }
    var attachContextMenu = function () {
        // open the context menu when the user presses the mouse right button.
        $("#jqxTree li").on('mousedown', function (event) {
            var target = $(event.target).parents('li:first')[0];
            temp=$(this).attr('class').split(' ');
            for(i=0;i<temp.length;i++){
                if(temp[i].indexOf('id_')!=-1){
                    temp1=temp[i].split('_');
                    id=temp1[1];
                    $("#id").val(id);
                }
                else if(temp[i].indexOf('level_')!=-1){
                    temp1=temp[i].split('_');
                    level=temp1[1];
                    $("#level").val(level);
                }
            }

            var rightClick = isRightClick(event);
            if (rightClick && target != null) {
                $("#jqxTree").jqxTree('selectItem', target);
                var scrollTop = $(window).scrollTop();
                var scrollLeft = $(window).scrollLeft();

                if(level=='0'){
                    contextMenuRoot.jqxMenu('open', parseInt(event.clientX) + 5 + scrollLeft, parseInt(event.clientY) + 5 + scrollTop);
                }
                else{
                    contextMenuAll.jqxMenu('open', parseInt(event.clientX) + 5 + scrollLeft, parseInt(event.clientY) + 5 + scrollTop);
                }

                return false;
            }
        });
    }
</script>
<script type="text/javascript">
        
    var clickedItem = null;
    var dialog,dialogEdit;
 
    $(document).ready(function () {
        // Create jqxTree
        $('#jqxTree').jqxTree({ height: '320px', width: '100%',toggleMode: 'click' });
        $('#jqxTree').css('visibility', 'visible');
        
        contextMenuAll = $("#jqxMenuAll").jqxMenu({ width: '200px',  height: 'auto', autoOpenPopup: false, mode: 'popup' });
        contextMenuRoot = $("#jqxMenuRoot").jqxMenu({ width: '200px',  height: 'auto', autoOpenPopup: false, mode: 'popup' });

        
        attachContextMenu();
        $("#jqxMenuRoot").on('itemclick', function (event) {
            var item = $.trim($(event.args).text());
            switch (item) {
                case "Thêm mục con":
                    dialog.dialog( "open" );
                    break;
            }
        });
        
        $("#jqxMenuAll").on('itemclick', function (event) {
            var item = $.trim($(event.args).text());
            switch (item) {
                case "Thêm mục con":
                    dialog.dialog( "open" );
                    break;
                case "Sửa mục này":
                    dialogEdit.dialog( "open" );
                    var selectedItem = $('#jqxTree').jqxTree('selectedItem');
                    $("#name_edit").val(selectedItem.label);
                    $.ajax({
                        url:'<?php echo $this->baseUrl();?>/chiase/getitem/id/'+id,
                        type:'GET',
                        async: true,
                        success: function (data1, textStatus, jqXHR) {
                            json = $.parseJSON(data1);
                            $("#content_edit").val($.trim(json.content));
                            if(json.is_public=="1"){
                                $("#is_public_edit").prop("checked",true);
                            }
                            else{
                                $("#is_public_edit").prop("checked",false);
                            }
                        }
                    });
                    break;
                case "Xóa mục này":
                    deleteItem('chiase',level,id);
                    var selectedItem = $('#jqxTree').jqxTree('selectedItem');
                    if (selectedItem != null) {
                        $('#jqxTree').jqxTree('removeItem', selectedItem.element);
                        attachContextMenu();
                    }
                    break;
            }
        });
        // disable the default browser's context menu.
        $(document).on('contextmenu', function (e) {
            if ($(e.target).parents('.jqx-tree').length > 0) {
                return false;
            }
            return true;
        });

        
        
        dialog = $( "#dialog-form" ).dialog({
            open: function( event, ui ) {
                $("li.has_children").css('z-index','0');
				$("#name").focus();

                },
              autoOpen: false,
              height: 600,
              width: 850,
              modal: true,
              buttons: [
                {
                  text: "Ok",
                  click: function() {
                    addMucCon('chiase',$("#name"))
                  }
                },
                {
                  text: "Hủy",
                  click: function() {
                    dialog.dialog( "close" );
                  }
                }
              ],
              close: function() {
                  $("#name").val('');
                  $("li.has_children").css('z-index','200');
              }
            });
            
            dialogEdit = $( "#dialog-form-edit" ).dialog({
                open: function( event, ui ) {
                    $("li.has_children").css('z-index','0');
					$("#name_edit").focus();
                },
              autoOpen: false,
              height: 600,
              width: 850,
              modal: true,
              buttons: [
                {
                  text: "Ok",
                  click: function() {
                    editItem('chiase',$("#name_edit"))
                  }
                },
                {
                  text: "Hủy",
                  click: function() {
                    dialogEdit.dialog( "close" );
                  }
                }
              ],
              close: function() {
                  $("#name_edit").val('');
                  $("li.has_children").css('z-index','200');
              }
            });

    });
</script>

<div id="dialog-form" title="Thêm mục con">
    <fieldset>
        <label for="is_public">Công khai: </label>
      <input type="checkbox" id="is_public" checked>
      <br>
      <label for="name">Tựa đề: </label>
      <input type="text" style="width:700px;" name="name" id="name" class="text ui-widget-content ui-corner-all">
      <br>
      <label for="content" style="float: left;">Nội dung: </label>
      <textarea id="content" name="content" cols="70" rows="50" style="float: left;"></textarea>
      
      <input type="hidden" name="id" id="id">
 
      <input type="submit" tabindex="-1" style="position:absolute; top:-1000px">
    </fieldset>
</div>

<div id="dialog-form-edit" title="Sửa">
    <fieldset>
        <label for="is_public_edit">Công khai: </label>
      <input type="checkbox" id="is_public_edit">
      <br>
      <label for="name_edit">Tựa đề: </label>
      <input type="text" style="width:700px;" name="name_edit" id="name_edit" class="text ui-widget-content ui-corner-all">
      <input type="hidden" name="id_edit" id="id_edit">
      <br>
      <label for="content_edit" style="float: left;">Nội dung: </label>
      <textarea id="content_edit" name="content_edit" cols="70" rows="50" style="float: left;"></textarea>
      
 
      <input type="submit" tabindex="-1" style="position:absolute; top:-1000px">
    </fieldset>
</div>


<div class="row-fluid" style="padding-top:20px;margin-bottom: 50px;">

    <div class="col-lg-12 col-md-12">
        <div id='jqxWidget'>
            <div id='jqxTree''>
                <ul>
                    <li id='home' class="id_0 level_0" item-selected='true'>
                        <?php 
                        echo 'Tất cả';
                        if(is_array($this->items)&&count($this->items)>0){
                            echoMuc($this->items,$this);
                        }
                        ?>
                    </li>
                    
                </ul>
            </div>
            <div id='jqxMenuRoot'>
                <ul>
                    <li>Thêm mục con</li>
                </ul>
            </div>
            <div id='jqxMenuAll'>
                <ul>
                    <li>Thêm mục con</li>
                    <li>Sửa mục này</li>
                    <li>Xóa mục này</li>
                </ul>
            </div>
            
        </div>
    </div>
</div>

<?php 
function echoMuc($items,$view){?>
    <ul>
        <?php                     
        foreach ($items as $item){?>
        <li class="id_<?php echo $item['id'];?>  level_1<?php if(trim($item['content'])!="") echo ' tree_has_content';?>">
                <?php 
                echo $item['title'];
                if($item['number_children'] > 0){
                    $items1 = array();
                    foreach ($view->items1 as $temp){
                        if ($temp['parent_id'] == $item['id']){
                            $items1[] = $temp;
                        }
                    }
                    echoMuc($items1,$view);
                    ?>
            <?php 

                }
                ?>
            </li>
        <?php 
        }
        ?>
    </ul>
<?php 
}
?>
