<?php 
$module=Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
$auth = Zend_Auth::getInstance();
if ($auth->hasIdentity()) {
    $identity = $auth->getIdentity();
}
else{
    $identity=NULL;
}
?>
<nav class="navbar navbar-default" style="margin-bottom: 5px;background: none;width: auto;border: none;">
        <ul class="nav navbar-nav" id="topnav">
            <?php 
            if($module=='default'){?>
                <li<?php if (Zend_Controller_Front::getInstance()->getRequest()->getControllerName() == 'index') echo ' class="active"'; ?>><a href="<?php echo $this->baseUrl(); ?>/">Trang chủ</a></li>
                <li<?php if (Zend_Controller_Front::getInstance()->getRequest()->getControllerName() == 'thanhvien') echo ' class="active"'; ?>><a href="<?php echo $this->baseUrl(); ?>/thanhvien">Thành viên</a></li>                        
                <?php 
                if(is_array($identity)&&$identity['is_upload']=='1'){?>
                <li<?php if (Zend_Controller_Front::getInstance()->getRequest()->getControllerName() == 'excel') echo ' class="active"'; ?>><a href="<?php echo $this->baseUrl(); ?>/excel">Nhập liệu</a></li>
                <?php
                }                
            }
            else { ?>
                <li<?php if (Zend_Controller_Front::getInstance()->getRequest()->getControllerName() == 'user') echo ' class="active"'; ?>><a href="<?php echo $this->baseUrl(); ?>/admin/user">User</a></li>
                <li<?php if (Zend_Controller_Front::getInstance()->getRequest()->getControllerName() == 'homecontent') echo ' class="active"'; ?>><a href="<?php echo $this->baseUrl(); ?>/admin/homecontent">Nội dung trang chủ</a></li>                                
                <li<?php if (Zend_Controller_Front::getInstance()->getRequest()->getControllerName() == 'image') echo ' class="active"'; ?>><a href="<?php echo $this->baseUrl(); ?>/admin/image">Logo và hình nền</a></li>
                <li<?php if (Zend_Controller_Front::getInstance()->getRequest()->getControllerName() == 'headerfooter') echo ' class="active"'; ?>><a href="<?php echo $this->baseUrl(); ?>/admin/headerfooter">Phía trên và phía dưới</a></li>
                <li<?php if (Zend_Controller_Front::getInstance()->getRequest()->getControllerName() == 'settings') echo ' class="active"'; ?>><a href="<?php echo $this->baseUrl(); ?>/admin/settings">Cài đặt</a></li>
            <?php 
            }
            ?>
        </ul>
</nav>