<?php 
$url = $this->url();
$temp = explode('page', $url);
if (is_array($temp) && count($temp) == 2) {
    $url = $temp[0];
}
?>
<form method="post" action="<?php echo $url; ?>">
    <div class="row">
        <div class="col-lg-12 col-md-12" style="text-align: center;">
            <?php if ($this->total > $this->limit) { ?>
                <table style="width: 100%;">
                    <tfoot>
                        <tr>
                            <td colspan="3" style="width: 100%;"><?php echo $this->paginationControl($this->paginator, 'Sliding', array('_partials/paginator.phtml', 'default')); ?></td>
                        </tr>
                    </tfoot>
                </table>
                <?php
            }
            ?>
        </div>
    </div>
</form>
