<?php
echo $this->doctype();
$db = Core_Db_Table::getDefaultAdapter();
$rows = $db->fetchAll('SELECT * FROM layout_content');
$logo = array('file_name' => '/images/dien_luc.jpg', 'dynamic' => '1');
$header_text = $header_text_dynamic = $footer_text = $hinh_nen = '';
foreach ($rows as $row) {
    $header_text = $row['header_text'];
    $header_text_dynamic = $row['dynamic_header_text'];
    $logo = array('file_name' => $row['file_name'], 'dynamic' => $row['dynamic_logo'],'show'=>$row['show']);
    $footer_text = $row['footer_text'];
    $hinh_nen = $row['hinh_nen_file_name'];
}
?>
<html>
    <head>
        <meta http-equiv="content-type" content="text/html;charset=utf-8;" />
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headScript() ?>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery-2.0.3.js"></script>
        <!--bootstrap-->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
              integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
                crossorigin="anonymous"></script> 
        <!--end bootstrap-->
        <!--menu-->
        <link href="<?php echo $this->baseUrl('/css/menu/menu.css'); ?>?<?php echo substr(str_shuffle(str_repeat($x='0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', ceil(10/strlen($x)) )),1,10);?>" media="screen" rel="stylesheet" type="text/css" />				 
        <!--end menu-->  
        <!-- top bottom-->
<!--        <link href="<?php echo $this->baseUrl(); ?>/css/top_bottom.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl(); ?>/css/style.css" rel="stylesheet" type="text/css"/>-->
        <!--end layout--> 

        <link rel="stylesheet" href="<?php echo $this->baseUrl('/jquery-ui-1.10.3/themes/smoothness/jquery-ui.css'); ?>" type="text/css"/>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/jquery-ui-1.10.3/ui/jquery-ui.js"></script>          

        <!--hiệu ứng chuyển động ảnh-->
        <?php
        if ($logo['dynamic'] == "1") {
            ?>
            <script type="text/javascript" src="<?php echo $this->baseUrl('/js/jquery.cycle.all.js'); ?>"></script>
            <?php
        }
        ?>
        <!--end hiệu ứng chuyển động ảnh-->
        <!--chạy chữ-->
        <?php
        if ($header_text_dynamic == "1" && trim($header_text) != '') {
            ?>
            <script type="text/javascript" src="<?php echo $this->baseUrl('/js/animation_text/textTyper.js'); ?>"></script>
            <?php
        }
        ?>
        <!--end chạy chữ-->     
        <script type="text/javascript">

            /**
             * end index.phtml
             **/
            jQuery(function ($) {
<?php
if ($logo['dynamic'] == "1") {
    ?>
                    $('#logo_header').cycle({
                        fx: 'zoom', sync: false, delay: -2000
                    });
    <?php
}
?>
<?php
if ($header_text_dynamic == "1" && trim($header_text) != '') {
    ?>
                    $('div#simpleDiv').textTyper({repeatAnimation: true, repeatTimes: 100, speed: 50});
    <?php
}
?>
            });
            
        </script>
        
        <style>
        
        
            form label:hover{
                background-color: #cccccc;
            }
            form label{
                cursor: pointer;
            }


        </style>

    </head>
    <body style="background:#f0f0f0;">

        <?php echo $this->render('index/dialog.phtml'); ?>
        <div class="container">
            <div class="row" style="padding-top: 30px;height: 100px;background-image: url('<?php echo $this->baseUrl($hinh_nen); ?>');background-repeat: no-repeat;background-size: 100% 100%;margin-bottom: 20px;margin-top: 20px;">
                <div class="col-lg-3 col-md-3">
                    <?php 
                    if($logo['show']=='1'){
                            if ($logo['dynamic'] == "1") {
                                ?>

                    <div class="col-lg-12 col-md-12" id="logo_header">
                                    <?php
                                    Core_Common_Image::echoImage($this->baseUrl($logo['file_name']), 70, 70, 'height', array('id' => 'logo-img'));
                                    Core_Common_Image::echoImage($this->baseUrl($logo['file_name']), 70, 70, 'height', array('id' => 'logo-img1'));
                                    ?>
                                </div>
                                <?php
                            } else {
                                ?>
                                <div class="col-lg-12 col-md-12" id="logo_header">
                                    <?php
                                    Core_Common_Image::echoImage($this->baseUrl($logo['file_name']), 70, 70, 'height', array('id' => 'logo-img'));
                                    ?>
                                </div>
                                <?php
                            }
                    }
                    else{
                        echo '&nbsp;';
                    }
                            ?>
                </div>
                <div class="col-lg-5 col-md-5">
                    <div class="row" <?php
                        if ($header_text_dynamic == "1" && trim($header_text) != '') {
                            echo ' id="simpleDiv"';
                        }
                        ?> style="font-size: 30px;line-height: 1.3;text-align: center;color: #c1976c;font-family: serif;padding-top: 0;">
                            <div class="col-lg-12 col-md-12"><?php echo $header_text; ?></div>
                        </div>  
                </div>
                <div class="col-lg-4 col-md-4">
                        <?php 
                            echo $this->render('index/auth.phtml'); 
                        ?>
                </div>
            </div>
            <div class="row" style="margin-bottom: 20px;">
                <?php echo $this->render('index/menu.phtml'); ?>
            </div>

            <?php 
            $bg=$this->bg;
            if($bg!=''){
                $bg='background-image: url('.$this->baseUrl($bg).');background-size: cover;-webkit-background-size: cover;background-repeat: no-repeat;';
            }
            else{
                $bg='background: white;';
            }
            ?>
            <div class="row" id="container" style="padding: 20px;min-height: 500px;<?php echo $bg;?>">
                <?php echo $this->layout()->content; ?>     
            </div>
            
            <div class="row" style="color:white;background-color: #c1976c;margin-top: 30px;margin-bottom: 30px;">	
                <div class="col-lg-12 col-md-12">
                    <?php
                    echo html_entity_decode($footer_text);
                    ?>
                </div>
            </div>


        </div><!-- /.container -->
    </body>
</html>