<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/ckeditor/ckeditor.js"></script>
<script type="text/javascript">
    jQuery(function ($) {
        CKEDITOR.replace('editor1', {
            language: 'en',
            filebrowserUploadUrl: '/upload.php'
        });
    });

</script>

<div class="row">
    <div class="col-lg-12 col-md-12">
        <textarea rows="" cols="" name="footer_text" id="editor1"><?php echo $this->footer_text; ?></textarea>
    </div>
</div>


